 SELECT _DATA:"CUSTOMER_ID"::NUMBER AS CUSTOMER_ID,
_DATA:"FIRST_NAME":: STRING AS  FIRST_NAME,
_DATA:"MIDDLE_NAME":: STRING AS  MIDDLE_NAME,
_DATA:"LAST_NAME":: STRING AS  LAST_NAME,
_DATA:"ACCOUNT_TYPE":: STRING AS  ACCOUNT_TYPE,
_DATA:"ACCOUNT_DETAILS"[0]:"Address":"Residential"::STRING AS  Residential,
_DATA:"ACCOUNT_DETAILS"[0]:"Address":"Billing"::STRING AS  Billing,
_DATA:"ACCOUNT_DETAILS"[0]:"Banking":"branch":: STRING AS branch,
_DATA:"ACCOUNT_DETAILS"[0]:"Banking":"accountNumber":: STRING AS accountNumber,
_DATA:"ACCOUNT_DETAILS"[0]:"Banking":"balance":: STRING AS BALANCE
from  MYDB.CASESTUDY_JSON.JSON_DATA
