 SELECT A.PRODUCT_ID ,A.PRODUCT_NAME,A.PRICE,A.STOCK FROM MYDB.POSTGREDB_STUDY_MYSCHEMA_TEST.STG_PRODUCTS A
 UNION ALL
  SELECT B.PRODUCT_ID,B.PRODUCT_NAME,B.PRICE,B.STOCK FROM  MYDB.CASESTUDY_PRODUCT.PRODUCT_DATA_XLS_SHEET_1 B